src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="posts")
     */
    private $created_by;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class PostType extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		dump($options['choices']);
		$builder
			->add('title', null, [
				'label'		=> 'Titre',
				'required'	=> true,
			])
			->add('content', null, [
				'label'		=> 'Contenu',
				'required'	=> true,
			])
			// ->add('weight', null, [
			// 	'label'		=> 'Poids',
			// 	'required'	=> true,
			// ])
			// ->add('unit', null, [
			// 	'label'		=> 'Unité',
			// 	'required'	=> true,
			// ])
			// ->add('coupeur', ChoiceType::class, $options['choices'], [
			// 	'label'		=> 'Sélection du coupeur',
			// 	'required'	=> true,
			// ])
			// ->add('chargeur', ChoiceType::class, $options['choices'], [
			// 	'label'		=> 'Sélection du chargeur',
			// 	'required'	=> true,
			// ])
			// ->add('chauffeur', ChoiceType::class, $options['choices'], [
			// 	'label'		=> 'Sélection du chauffeur',
			// 	'required'	=> true,
			// ])
		;
	}

	public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults([
			'data_class' => Post::class,
			'choices' => null,
		]);
	}
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Post;
use App\Form\PostType;
use App\Repository\PostRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 */
class PostController extends Controller
{
	// /**
	//  * Accessible only for ``ADMIN`` and allow the acess to all tickets
	//  *
	//  * @param TicketRepository $ticketRepository
	//  * @return Response
	//  *
	//  * @Route("/admin/ticket/", name="ticket_index", methods="GET")
	//  */
	// public function index(TicketRepository $ticketRepository): Response
	// {
	// 	return $this->render('ticket/index.html.twig', ['tickets' => $ticketRepository->findAll()]);
	// }

	/**
	 * Controller to create a new ticket
	 *
	 * @param Request $request
	 * @return Response
	 *
	 *  @Route("/post/new", name="post_new", methods="GET|POST")
	 */
	public function new(Request $request): Response
	{

		$em = $this->getDoctrine()->getManager();
		// $em = $this->getEntityManager();
		// $repoU = $em->getRepository(User::class);
		// $users = $repoU->findAll();

		// $userChoices = array();
		// foreach($users as $u){
		//     // TODO
		// }

		// $choices = ['choices' => $users];

		// $choice_labels = function($user, $key, $value) {
		// 	/** @var User $user */
		// 	return strtoupper($user->getEmail());
		// };

		// $choices_pref = function($user, $key, $value) {
		// 	return $user->getId() == $this->getUser()->getId();
		// };

		// $choices = ['choices' => [
		// 	'choices' => $users,
		// 	'choice_label' => $choice_labels,
		// 	'preferred_choices' => $choices_pref
		// ]];

		// dump($choices); // DEBUG
		$post = new Post();
		$form = $this->createForm(PostType::class, $post);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			$post->setCreatedAt(new \DateTime());
			$em = $this->getDoctrine()->getManager();
			$em->persist($post);
			$em->flush();

			return $this->redirectToRoute('connected_homepage');
		}

		return $this->render('post/new.html.twig', [
			'post' => $post,
			'form' => $form->createView(),
		]);
	}

	/**
	 * Controller to retrieve a single ticket
	 *
	 * @param Post $post
	 * @return Response
	 *
	 * @Route("/post/{id}", name="post_show", methods="GET")
	 */
	public function show(Post $post): Response
	{
		return $this->render('post/show.html.twig', ['post' => $post]);
	}

	/**
	 * Controller to edit a post
	 *
	 * @param Request $request
	 * @param Post $post
	 * @return Response
	 *
	 * @Route("/admin/post/{id}/edit", name="post_edit", methods="GET|POST")
	 */
	public function edit(Request $request, Post $post): Response
	{
		$form = $this->createForm(PostType::class, $post);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			$this->getDoctrine()->getManager()->flush();

			return $this->redirectToRoute('post_edit', ['id' => $post->getId()]);
		}

		return $this->render('post/edit.html.twig', [
			'post' => $post,
			'form' => $form->createView(),
		]);
	}

	// /**
	//  * Controller to delete a ticket
	//  *
	//  * @param Request $request
	//  * @param Ticket $ticket
	//  * @return Response
	//  *
	//  * @Route("/admin/ticket/{id}", name="ticket_delete", methods="DELETE")
	//  */
	// public function delete(Request $request, Ticket $ticket): Response
	// {
	// 	if ($this->isCsrfTokenValid('delete'.$ticket->getId(), $request->request->get('_token'))) {
	// 		$em = $this->getDoctrine()->getManager();
	// 		$em->remove($ticket);
	// 		$em->flush();
	// 	}

	// 	return $this->redirectToRoute('ticket_index');
	// }
}

templates/post/_delete_form.html.twig
<form method="post" action="{{ path('post_delete', {'id': post.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="btn">Delete</button>
</form>

templates/post/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <br>
    <button class="btn btn-success btn-save">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la publication{% endblock %}

{% block body %}
    <h1>Edit Post</h1>

    {{ include('post/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('post_index') }}">retour à la liste</a>

    {{ include('post/_delete_form.html.twig') }}
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}AssurAimant | Les publications{% endblock %}

{% block body %}
    <h3>Mes posts</h3>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Contenu</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr>
                <td>{{ post.id }}</td>
                <td>{{ post.title }}</td>
                <td>{{ post.content|length > 15 ? post.content|slice(0, 15) ~ '...' : post.content }}</td>
                <td>{{ post.createdAt ? post.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('post_show', {'id': post.id}) }}"><i class="fa fa-info-circle green"></i> Détails</a><br>
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('post_edit', {'id': post.id}) }}"><i class="fa fa-edit green"></i> Modifier</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('post_new') }}"><button class="btn btn-success btn-save">New post</button></a>
    {% endif %}
{% endblock %}

templates/post/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Post{% endblock %}

{% block body %}
    <h1>Créer un nouveau Post</h1>

    <hr>

    {{ include('post/_form.html.twig') }}

    <a href="{{ path('connected_homepage') }}"><button class="btn btn-default btn-back">Retrouner à la liste</button></a>
{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post{% endblock %}

{% block body %}
	<h1>Post</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ post.id }}</td>
			</tr>
			<tr>
				<th>Titre</th>
				<td>{{ post.title }}</td>
			</tr>
			<tr>
				<th>Contenu</th>
				<td>{{ post.content|raw }}</td>
			</tr>
			<tr>
				<th>Date</th>
				<td>{{ post.createdAt ? post.createdAt|date('Y-m-d H:i:s') : '' }}</td>
			</tr>
		</tbody>
	</table>
		<a href="{{path('connected_homepage')}}"><button class="btn btn-default btn-back">Back</button></a>

	{% if is_granted('ROLE_ADMIN') %}
		<a href="{{ path('post_edit', {'id': post.id}) }}">edit</a>
	{{ include('post/_delete_form.html.twig') }}
	{% endif %}

{% endblock %}